CREATE DATABASE UnholyForest;
USE UnholyForest;

CREATE TABLE user (
	id INT NOT NULL AUTO_INCREMENT, 
	name VARCHAR(16) NOT NULL, 
	passwd VARCHAR(32) NOT NULL, 
);

CREATE TABLE series (
	id INT NOT NULL AUTO_INCREMENT, 
	name VARCHAR(64) NOT NULL, 
	intro VARCHAR(128) NOT NULL, 
);

CREATE TABLE article (
	id INT NOT NULL AUTO_INCREMENT, 
	sid INT NOT NULL, 
	pid INT NOT NULL, 
	level INT NOT NULL, 
	author INT NOT NULL, 
	name VARCHAR(64) NOT NULL, 
	content VARCHAR(16384) NOT NULL, 
	time TIMESTAMP NOT NULL, 
);
